---
- name: Create a directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: /mnt/data
    state: directory
    mode: '0755'
- name: Create a new ext4 primary partition
  become: yes
  community.general.parted:
    device: /dev/sdb
    number: 1
    state: present
    fs_type: ext4
- name: Create a ext4 filesystem on /dev/sdb1
  become: yes
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sdb1
- name: Mount volume on /mnt/data
  become: yes
  ansible.posix.mount:
    path: /mnt/data
    src: /dev/sdb1
    state: present
    fstype: ext4
